// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Invalidation } from "./Invalidation";

export type ErrorReason = "BadRequest" | { "Invalid": { [key in string]?: Invalidation } } | "Unauthorized" | "Forbidden" | "NotFound" | "Conflict" | "Internal" | "ServiceUnavailable" | "GatewayTimeout";
