/* eslint-disable */
// @ts-nocheck
/*    @@@@@@@@@@@@@ & ###############
   @@@@@@@@@@@@@@ &&& ###############
 @@@@@@@@@@@@@@ &&&&& ###############
############### &&&&& ###############
######## Generated by Qubit! ########
############### &&&&& ###############
############### &&&&& @@@@@@@@@@@@@@
############### && @@@@@@@@@@@@@@
############### & @@@@@@@@@@@@@    */

import type { ErrorReason } from "./ErrorReason.ts";
import type { ErrorResponse } from "./ErrorResponse.ts";
import type { UserRegistration } from "./UserRegistration.ts";
import type { Mutation } from "@qubit-rs/client";

export type { ErrorReason } from "./ErrorReason.ts";
export type { ErrorResponse } from "./ErrorResponse.ts";
export type { UserRegistration } from "./UserRegistration.ts";
export type { Mutation } from "@qubit-rs/client";

export type QubitServer = { register: Mutation<[user: UserRegistration, ], { Ok : string } | { Err : ErrorResponse }> };