// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 *This is a restructured (View) model of ['UserAll']. Refer to the original model for more structual documentation.
 */
export type UserRegistration = { username: string, password: string, email: string, };
